services:
  nutrividax:
    image: nginx:alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nutrividax.rule=Host(`nutrividax.com`,`www.nutrividax.com`)"
      - "traefik.http.routers.nutrividax.entrypoints=web,websecure"
      - "traefik.http.routers.nutrividax.tls=true"
      - "traefik.http.routers.nutrividax.tls.certresolver=myresolver"
      - "traefik.http.services.nutrividax.loadbalancer.server.port=80"
    networks:
      - traefik

networks:
  traefik:
    external: true

