name: Build and Deploy to Hostinger via FTP

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Preflight - validar secrets/variables
        shell: bash
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER || vars.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME || vars.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD || vars.FTP_PASSWORD }}
          FTP_SERVER_DIR: ${{ secrets.FTP_SERVER_DIR || vars.FTP_SERVER_DIR }}
        run: |
          missing=0
          for v in FTP_SERVER FTP_USERNAME FTP_PASSWORD FTP_SERVER_DIR; do
            if [ -z "${!v}" ]; then
              echo "::error::Missing required secret/variable: $v"
              missing=1
            fi
          done
          if [ "$missing" -ne 0 ]; then
            echo "::error::Configure os secrets ou variables exigidos em Settings > Secrets and variables > Actions"
            exit 1
          fi
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Listar conteúdo de dist (incluindo ocultos)
        run: |
          shopt -s dotglob
          ls -la dist

      - name: Deploy via FTPS
        id: deploy_ftps
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER || vars.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME || vars.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD || vars.FTP_PASSWORD }}
          port: 21
          local-dir: dist/
          server-dir: ${{ secrets.FTP_SERVER_DIR || vars.FTP_SERVER_DIR }}
          protocol: ftps
          security: loose
          # Remove todos os arquivos antigos antes do upload (use com cuidado)
          dangerous-clean-slate: true

      - name: Deploy via FTP (fallback se FTPS falhar)
        if: steps.deploy_ftps.outcome == 'failure'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER || vars.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME || vars.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD || vars.FTP_PASSWORD }}
          port: 21
          local-dir: dist/
          server-dir: ${{ secrets.FTP_SERVER_DIR || vars.FTP_SERVER_DIR }}
          protocol: ftp
          # Remove todos os arquivos antigos antes do upload (use com cuidado)
          dangerous-clean-slate: true
